In [1]:
import pandas as pd
import numpy as np
import warnings

In [2]:
warnings.filterwarnings('ignore')

# Diabetes Dataset

In [18]:
X_trainData = pd.read_csv("Diabetes_XTrain.csv")
Y_trainData = pd.read_csv("Diabetes_YTrain.csv")
X_testData = pd.read_csv("Diabetes_XTest.csv")
Y_testData = pd.read_csv("sample_submission.csv")

In [19]:
print(X_trainData.shape)
print(Y_trainData.shape)
print(X_testData.shape)
print(Y_testData.shape)

(576, 8)
(576, 1)
(192, 8)
(192, 1)

In [20]:
X_trainData

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,7,168,88,42,321,38.2,0.787,40
1,8,110,76,0,0,27.8,0.237,58
2,7,147,76,0,0,39.4,0.257,43
3,2,100,66,20,90,32.9,0.867,28
4,4,129,86,20,270,35.1,0.231,23
...,...,...,...,...,...,...,...,...
571,2,111,60,0,0,26.2,0.343,23
572,7,187,68,39,304,37.7,0.254,41
573,2,122,60,18,106,29.8,0.717,22
574,4,154,72,29,126,31.3,0.338,37
575,1,88,78,29,76,32.0,0.365,29

In [21]:
X_trainData['Is diabetic ?'] = Y_trainData

In [27]:
X_trainData
pd.DataFrame(X_trainData).head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Is diabetic ?
0,7,168,88,42,321,38.2,0.787,40,1
1,8,110,76,0,0,27.8,0.237,58,0
2,7,147,76,0,0,39.4,0.257,43,1
3,2,100,66,20,90,32.9,0.867,28,1
4,4,129,86,20,270,35.1,0.231,23,0
5,7,100,0,0,0,30.0,0.484,32,1
6,4,110,66,0,0,31.9,0.471,29,0
7,1,111,86,19,0,30.1,0.143,23,0
8,3,169,74,19,125,29.9,0.268,31,1
9,1,71,62,0,0,21.8,0.416,26,0

# KNN Algorithm

In [46]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

def knn(X,Y,queryPoint,k=5):
    
    vals = []
    m = X.shape[0]
    
    for i in range(m):
        d = dist(queryPoint,X[i])
        vals.append((d,Y[i]))
        
    
    vals = sorted(vals)
    # Nearest/First K points
    vals = vals[:k]
    
    vals = np.array(vals)
    
    #print(vals)
    
    new_vals = np.unique(vals[:,1],return_counts=True)
    #print(new_vals)
    
    index = new_vals[1].argmax()
#     print(index)
    pred = new_vals[0][index]
    
    return pred

In [47]:
X_trainDatanumpy = np.array(X_trainData)
Y_trainDatanumpy = np.array(Y_trainData)
X_testDatanumpy = np.array(X_testData)
Y_testDatanumpy = np.array(Y_testData)

# Prediction if Diabetic or not

In [107]:
X_testData['isDiabetic'] = Y_testData
X_testData.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,isDiabetic
0,0,180,90,26,90,36.5,0.314,35,1
1,2,93,64,32,160,38.0,0.674,23,1
2,2,114,68,22,0,28.7,0.092,25,1
3,13,76,60,0,0,32.8,0.180,41,1
4,1,80,74,11,60,30.0,0.527,22,1
5,5,137,108,0,0,48.8,0.227,37,1
6,1,153,82,42,485,40.6,0.687,23,1
7,6,98,58,33,190,34.0,0.430,43,1
8,2,92,62,28,0,31.6,0.130,24,1
9,3,111,56,39,0,30.1,0.557,30,1

In [108]:
def isDiabetic():
    ifDiabetic = knn(X_trainDatanumpy[:,:8], Y_trainDatanumpy, X_testDatanumpy[5])
    return ifDiabetic[0]

In [109]:
if isDiabetic() == 0:
    print("Not Diabetic")
else:
    print("Diabetic")

Diabetic

In [93]:
def accuracy():
    sum = 0
    for i in range(0,X_testDatanumpy.shape[0]):
        if(knn(X_trainDatanumpy[:,:8], Y_trainDatanumpy, X_testDatanumpy[i])[0] == Y_testDatanumpy[i]):
            sum = sum + 1
    return sum/(X_testDatanumpy.shape[0])*100

In [97]:
str(accuracy()) + "%"

'32.8125%'